package entities;
// Generated Jul 29, 2015 11:12:29 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MovieGenreId generated by hbm2java
 */
@Embeddable
public class MovieGenreId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6385602824263519372L;
	private int idMovie;
	private int idGenre;

	public MovieGenreId() {
	}

	public MovieGenreId(int idMovie, int idGenre) {
		this.idMovie = idMovie;
		this.idGenre = idGenre;
	}

	@Column(name = "idMovie", nullable = false)
	public int getIdMovie() {
		return this.idMovie;
	}

	public void setIdMovie(int idMovie) {
		this.idMovie = idMovie;
	}

	@Column(name = "idGenre", nullable = false)
	public int getIdGenre() {
		return this.idGenre;
	}

	public void setIdGenre(int idGenre) {
		this.idGenre = idGenre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MovieGenreId))
			return false;
		MovieGenreId castOther = (MovieGenreId) other;

		return (this.getIdMovie() == castOther.getIdMovie()) && (this.getIdGenre() == castOther.getIdGenre());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMovie();
		result = 37 * result + this.getIdGenre();
		return result;
	}

}
