package entities;
// Generated Jul 29, 2015 11:12:29 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MovieGenre generated by hbm2java
 */
@Entity
@Table(name = "MovieGenre", catalog = "PopcornFlavor")
public class MovieGenre implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9056161707107250298L;
	private MovieGenreId id;

	public MovieGenre() {
	}

	public MovieGenre(MovieGenreId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idMovie", column = @Column(name = "idMovie", nullable = false) ),
			@AttributeOverride(name = "idGenre", column = @Column(name = "idGenre", nullable = false) ) })
	public MovieGenreId getId() {
		return this.id;
	}

	public void setId(MovieGenreId id) {
		this.id = id;
	}

}
