package entities;
// Generated Jul 29, 2015 11:12:29 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "Movie", catalog = "PopcornFlavor")
public class Movie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -428361522075395439L;
	private Integer idMovie;
	private String title;
	private String beginYear;
	private String endYear;
	private String type;
	private String plot;
	private Integer totalVoters;
	private Integer totalRating;
	private String img;

	public Movie() {
	}

	public Movie(String title, String beginYear, String type, String plot) {
		this.title = title;
		this.beginYear = beginYear;
		this.type = type;
		this.plot = plot;
	}

	public Movie(String title, String beginYear, String endYear, String type, String plot, Integer totalVoters,
			Integer totalRating, String img) {
		this.title = title;
		this.beginYear = beginYear;
		this.endYear = endYear;
		this.type = type;
		this.plot = plot;
		this.totalVoters = totalVoters;
		this.totalRating = totalRating;
		this.img = img;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMovie", unique = true, nullable = false)
	public Integer getIdMovie() {
		return this.idMovie;
	}

	public void setIdMovie(Integer idMovie) {
		this.idMovie = idMovie;
	}

	@Column(name = "title", nullable = false, length = 240)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "beginYear", nullable = false, length = 10)
	public String getBeginYear() {
		return this.beginYear;
	}

	public void setBeginYear(String beginYear) {
		this.beginYear = beginYear;
	}

	@Column(name = "endYear", length = 10)
	public String getEndYear() {
		return this.endYear;
	}

	public void setEndYear(String endYear) {
		this.endYear = endYear;
	}

	@Column(name = "type", nullable = false, length = 6)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "plot", nullable = false, length = 1000)
	public String getPlot() {
		return this.plot;
	}

	public void setPlot(String plot) {
		this.plot = plot;
	}

	@Column(name = "totalVoters")
	public Integer getTotalVoters() {
		return this.totalVoters;
	}

	public void setTotalVoters(Integer totalVoters) {
		this.totalVoters = totalVoters;
	}

	@Column(name = "totalRating")
	public Integer getTotalRating() {
		return this.totalRating;
	}

	public void setTotalRating(Integer totalRating) {
		this.totalRating = totalRating;
	}

	@Column(name = "img", length = 45)
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

}
